poll txn status - dummy apis
roverxio/toad pull request #273
Opened 2023-08-23 10:23 UTC by viv-defy

2023-08-30 12:20 UTC, vishnukvnvv requested changes

2023-08-30 13:02 UTC, vishnukvnvv requested changes

2023-08-30 13:22 UTC, vishnukvnvv approved these changes

2023-08-30 14:22 UTC, ska1296 commented on bundler/src/handlers/wallet.rs
> +    wallet_dao: Data<WalletDao>,
can start with this till we streamline the entire thing.
A better approach might be to introduce a new function in the dao layer.

2023-08-30 14:22 UTC, ska1296 approved these changes

2023-08-31 05:27 UTC, vishnukvnvv approved these changes

2023-08-31 05:27 UTC, merged